model: WNO
equation: Phi41+
data: Phi41+1_xi_trc256

data_path: '../../data_gen/results/${equation}/${data}.mat'
dim_x: 128
T: 51
sub_t: 1

width: 128  # grid search: [32,64,96,128]
# Used in SPDEBench: Phi41+sigma1:128, Phi41+sigma1_Harr:128
L: 4
level: 3   # grid search: [3, 4]
# Used in SPDEBench: Phi41+sigma1:4, Phi41+sigma1_Harr:3

ntrain: 800
nval: 200
ntest: 200
batch_size: 20
epochs: 1000
learning_rate: 0.001
weight_decay: 1e-4
scheduler_step: 50
scheduler_gamma: 0.75
#plateau_patience: 50
delta: 1e-6
plateau_terminate: 100

print_every: 50

seed: 3407

save_dir: '../result/${model}_${equation}/'
checkpoint_file: '${data}.pth'

log_file: '${data}_log'